<div class="row">
	<div class="col-md-12">
		<h1><?php echo $autor->getAutorNombre() ?></h1>
		<form name="AutorForm" method="POST" action="/autor/editar/<?php echo $autor->getIdautor() ?>">
			<div class="form-group">
			    <label>Nombre</label>
			    <?php echo $this->formText($form->get('autor_nombre')) ?>

			    <label>País</label>
			    <?php echo $this->formSelect($form->get('autor_pais')) ?>

			    <input type="submit" value="Guardar" class="btn btn-success">
			 </div>
		</form>
	</div>
</div>