<div class="row">
	<div class="col-md-12">
		<h1>Autor</h1>
		<a href="/autor/nuevo">Nuevo</a>
		<table class="table table-bordered">
			<thead>
				<th>Id</th>
				<th>Nombre</th>
				<th>País</th>
				<th>Opciones</th>
			</thead>
			<tbody>
				<?php foreach($autores as $autor): ?>
					<tr>
						<td><?php echo $autor->getIdautor() ?></td>
						<td><?php echo $autor->getAutorNombre() ?></td>
						<td><?php echo $autor->getAutorPais() ?></td>
						<td>
							<a href="/autor/editar/<?php echo $autor->getIdautor() ?>">Editar</a>
							<a href="/autor/eliminar/<?php echo $autor->getIdautor() ?>">Eliminar</a>
						</td>
						
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

