<div class="row">
	<div class="col-md-12">
		<h1><?php echo $editorial->getEditorialNombre() ?></h1>
		<form name="EditorialForm" method="POST" action="/editorial/editar/<?php echo $editorial->getIdeditorial() ?>">
			<div class="form-group">
			    <label>Nombre</label>
			    <?php echo $this->formText($form->get('editorial_nombre')) ?>

			    <input type="submit" value="Guardar" class="btn btn-success">
			 </div>
		</form>
	</div>
</div>