<div class="row">
	<div class="col-md-12">
		<h4>Estas seguro que desea eliminar la editorial <b><?php echo $editorial->getEditorialNombre() ?>?</h4>
		<form name="EditorialForm" method="POST" action="/editorial/eliminar/<?php echo $editorial->getIdeditorial() ?>">
			<div class="form-group">
			 

			    <input type="submit" value="Eliminar" class="btn btn-danger">
			 </div>
		</form>
	</div>
</div>