<div class="row">
	<div class="col-md-12">
		<h1>Editorial</h1>
		<a href="/editorial/nuevo">Nuevo</a>
		<table class="table table-bordered">
			<thead>
				<th>Id</th>
				<th>Nombre</th>
				<th>Opciones</th>
			</thead>
			<tbody>
				<?php foreach($editoriales as $editorial): ?>
					<tr>
						<td><?php echo $editorial->getIdeditorial() ?></td>
						<td><?php echo $editorial->getEditorialNombre() ?></td>
						<td>
							<a href="/editorial/editar/<?php echo $editorial->getIdeditorial() ?>">Editar</a>
							<a href="/editorial/eliminar/<?php echo $editorial->getIdeditorial() ?>">Eliminar</a>
						</td>
						
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

