<div class="row">
	<div class="col-md-12">
		<h1><?php echo $libro->getLibroNombre() ?></h1>
		<form name="AutorForm" method="POST" action="/libro/editar/<?php echo $libro->getIdlibro() ?>">
			<div class="form-group">
			    <label>Nombre</label>
			    <?php echo $this->formText($form->get('libro_nombre')) ?>

			    <label>Autor</label>
			    <?php echo $this->formSelect($form->get('idautor')) ?>

			    <label>Editorial</label>
			    <?php echo $this->formSelect($form->get('ideditorial')) ?>

			    <input type="submit" value="Editar" class="btn btn-success">
			 </div>
		</form>
	</div>
</div>